-- MySQL Script generated by MySQL Workbench
-- Thu May  6 21:45:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`支行`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`支行` (
  `支行名` VARCHAR(25) NOT NULL,
  `城市` VARCHAR(20) NULL,
  `资产` INT NULL,
  PRIMARY KEY (`支行名`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`客户`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`客户` (
  `客户身份证号` VARCHAR(25) NOT NULL,
  `姓名` VARCHAR(45) NULL,
  `电话` INT NULL,
  `住址` VARCHAR(45) NULL,
  PRIMARY KEY (`客户身份证号`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`贷款`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`贷款` (
  `贷款号` VARCHAR(25) NOT NULL,
  `支行名` VARCHAR(25) NULL,
  `金额` INT NULL,
  `客户身份证号` VARCHAR(25) NULL,
  PRIMARY KEY (`贷款号`),
  INDEX `bank_name_idx` (`支行名` ASC) VISIBLE,
  INDEX `custom_id_idx` (`客户身份证号` ASC) VISIBLE,
  CONSTRAINT `bank_name`
    FOREIGN KEY (`支行名`)
    REFERENCES `mydb`.`支行` (`支行名`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `custom_id`
    FOREIGN KEY (`客户身份证号`)
    REFERENCES `mydb`.`客户` (`客户身份证号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`支付`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`支付` (
  `贷款号` VARCHAR(25) NOT NULL,
  `支付日期` DATE NOT NULL,
  `金额` INT NULL,
  PRIMARY KEY (`贷款号`, `支付日期`),
  CONSTRAINT `loan_id`
    FOREIGN KEY (`贷款号`)
    REFERENCES `mydb`.`贷款` (`贷款号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`部门`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`部门` (
  `部门号` INT NOT NULL,
  `支行名` VARCHAR(25) NULL,
  `经理身份证号` VARCHAR(25) NULL,
  `经理姓名` VARCHAR(45) NULL,
  `部门类型` VARCHAR(45) NULL,
  PRIMARY KEY (`部门号`),
  INDEX `bank_name_idx` (`支行名` ASC) VISIBLE,
  INDEX `employee_id_idx` (`经理身份证号` ASC) VISIBLE,
  CONSTRAINT `bank_name2`
    FOREIGN KEY (`支行名`)
    REFERENCES `mydb`.`支行` (`支行名`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_id`
    FOREIGN KEY (`经理身份证号`)
    REFERENCES `mydb`.`员工` (`员工身份证号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`员工`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`员工` (
  `员工身份证号` VARCHAR(25) NOT NULL,
  `部门号` INT NULL,
  `姓名` VARCHAR(45) NULL,
  `电话` INT NULL,
  `住址` VARCHAR(45) NULL,
  `开始工作时间` DATE NULL,
  PRIMARY KEY (`员工身份证号`),
  INDEX `department_id_idx` (`部门号` ASC) VISIBLE,
  CONSTRAINT `department_id`
    FOREIGN KEY (`部门号`)
    REFERENCES `mydb`.`部门` (`部门号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`负责`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`负责` (
  `员工身份证号` VARCHAR(25) NOT NULL,
  `客户身份证号` VARCHAR(25) NOT NULL,
  `负责类型` VARCHAR(45) NULL,
  PRIMARY KEY (`员工身份证号`, `客户身份证号`),
  INDEX `custom_id_idx` (`客户身份证号` ASC) VISIBLE,
  CONSTRAINT `employee_id2`
    FOREIGN KEY (`员工身份证号`)
    REFERENCES `mydb`.`员工` (`员工身份证号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `custom_id2`
    FOREIGN KEY (`客户身份证号`)
    REFERENCES `mydb`.`客户` (`客户身份证号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`账户`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`账户` (
  `账户号` VARCHAR(45) NOT NULL,
  `余额` INT NULL,
  `支行名` VARCHAR(25) NULL,
  `开户日期` DATE NULL,
  PRIMARY KEY (`账户号`),
  INDEX `bank_name_idx` (`支行名` ASC) VISIBLE,
  CONSTRAINT `bank_name3`
    FOREIGN KEY (`支行名`)
    REFERENCES `mydb`.`支行` (`支行名`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`储蓄账户`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`储蓄账户` (
  `账户号` VARCHAR(45) NOT NULL,
  `余额` INT NULL,
  `利率` FLOAT NULL,
  PRIMARY KEY (`账户号`),
  CONSTRAINT `account_id`
    FOREIGN KEY (`账户号`)
    REFERENCES `mydb`.`账户` (`账户号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`支票账户`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`支票账户` (
  `账户号` VARCHAR(45) NOT NULL,
  `余额` INT NULL,
  `透支额度` INT NULL,
  PRIMARY KEY (`账户号`),
  CONSTRAINT `account_id2`
    FOREIGN KEY (`账户号`)
    REFERENCES `mydb`.`账户` (`账户号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`拥有`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`拥有` (
  `账户号` VARCHAR(45) NOT NULL,
  `客户身份证号` VARCHAR(25) NULL,
  `最近访问日期` DATE NULL,
  PRIMARY KEY (`账户号`),
  INDEX `custom_id_idx` (`客户身份证号` ASC) VISIBLE,
  CONSTRAINT `account_id3`
    FOREIGN KEY (`账户号`)
    REFERENCES `mydb`.`账户` (`账户号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `custom_id3`
    FOREIGN KEY (`客户身份证号`)
    REFERENCES `mydb`.`客户` (`客户身份证号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`联系人`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`联系人` (
  `联系人姓名` VARCHAR(45) NOT NULL,
  `客户身份证号` VARCHAR(45) NOT NULL,
  `联系人电话` INT NULL,
  `联系人住址` VARCHAR(45) NULL,
  `联系人cemail` VARCHAR(45) NULL,
  `联系人关系` VARCHAR(45) NULL,
  PRIMARY KEY (`联系人姓名`, `客户身份证号`),
  INDEX `custom_id_idx` (`客户身份证号` ASC) VISIBLE,
  CONSTRAINT `custom_id4`
    FOREIGN KEY (`客户身份证号`)
    REFERENCES `mydb`.`客户` (`客户身份证号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
